# This is a basic workflow to help you get started with Actions

name: Reporting

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: install modules
        run: |
          yarn install
          git worktree add report

      - name: Coverage
        run: yarn coverage

      - name: ESdoc
        run: yarn doc

      - name: Static analysis
        run: yarn plato

      - name: git setting
        run: |
          git config --local user.email "tokutomi@degino.com"
          git config --local user.name "Tommy109"

      - name: git commit & push
        run: |
          cd report
          git pull
          git add .
          git commit -m 'Reports auto update'
          git push origin report
